version: "3.7"
services:
    kafka:
        #command: tail -F anything
        container_name: confluent-kafka-standalone
        privileged: true
        expose:
            - "9092"
            - "9021"
            - "8082"
        ports:
            - "9092:9092"
            - "9021:9021"
            - "8082:8082"
        build:
            context: .
            dockerfile: kafka/confluent-kafka-standalone.dockerfile         
        networks:
            kafka_lan:
                ipv4_address: 10.91.120.90
                aliases:
                    - kafka

networks:
    kafka_lan:
        name: bridge_kafka_lan
        driver: bridge 
        ipam:
            config:
              - subnet: 10.91.120.0/24
